### ISSUE TITLE
CLINEOS_REQ

### ISSUE THREAD

**Issue by MariemSahli** [it-Customer-team/java-team#3]
inverser la recherche dans getPersonByNeolid:  voir CLRID puis  CLDEC et mettre à jour CLDEC si pas trouvé.

**Comment by AbdellatifBoudalh** [comment]
CLINEOS_REQ ne consulte plus CLDEC. 
Elle réalise uniquement la conversion NEOLID => parcli/numcli/numfic ou  numpro/numfip
ou dans l'autre sens : parcli/numcli/numfic ou  numpro/numfip ==> NEOLID
